【Flutter研修: Tutorial5】MVVMを学ぶ
azusa-f/flutter-tutorial pull request #11
Opened 2022-04-07 07:49 UTC by azusa-f

### 概要
・Flutter研修　[Tutorial5  - MVVMを学ぶ](https://www.notion.so/Tutorial5-MVVM-b61b3274a2c14b09917ea4f17e09b641)に沿って、qiitaの記事をAPIで取得して表示する画面を作成。

### 仕様
・カテゴリーボタンを押すと、それに関連した記事が表示される。

https://user-images.githubusercontent.com/98789438/162147936-410d1d6e-8cdb-4eae-aec9-c69d2e39884d.mov

2022-04-07 13:23 UTC, t-nakata requested changes

2022-04-07 13:23 UTC, t-nakata commented on lib/mvvm/model/qiita_item.dart
> +    @JsonKey(name: "uel") String? uel,
タイポ urlです。

2022-04-07 13:23 UTC, t-nakata commented on lib/mvvm/qiita_client_state_notifier.dart
> +          qiitaItems: qiitaItems);
カンマがないです

2022-04-08 00:34 UTC, azusa-f commented
@t-nakata 
レビューありがとうございます。修正しました。

2022-04-08 00:45 UTC, t-nakata approved these changes

2022-04-08 00:53 UTC, merged