【Flutter研修: Tutorial６】API（Firebase）連携を学ぶ（YouTube画面）
azusa-f/flutter-tutorial pull request #12
Opened 2022-04-11 05:54 UTC by azusa-f

2022-04-11 11:19 UTC, t-nakata requested changes

2022-04-11 11:19 UTC, t-nakata commented on lib/youtube/state/youtube_state.dart
> +    @Default('') String currentTag,
currentTagはYoutubeStateには不要なので削除してください。

2022-04-11 11:19 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  Widget _buildPopularMovieSection(videoItems) {
ちゃんと引数の方を書いてください

2022-04-11 11:19 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  List<Widget> _buildVideoItems(videoItems) {
ちゃんと引数の方を書いてください

2022-04-11 11:20 UTC, t-nakata commented
lib/mvvm/model/qiita_item.freezed.dart このファイルを削除していますが、qiitaAPIの画面はちゃんと動作しますか？

2022-04-12 00:26 UTC, azusa-f commented on lib/youtube/state/youtube_state.dart
> +    @Default('') String currentTag,
削除しました

2022-04-12 00:34 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  List<Widget> _buildVideoItems(videoItems) {
List<YoutubeItem> videoItems

2022-04-13 02:20 UTC, azusa-f commented
> lib/mvvm/model/qiita_item.freezed.dart このファイルを削除していますが、qiitaAPIの画面はちゃんと動作しますか？

動作しなさそうなので、戻しました。

修正したので、確認お願いいたします。

2022-04-13 03:46 UTC, azusa-f commented on lib/youtube/youtube_screen.dart
> +  Widget _buildPopularMovieSection(videoItems) {
型書きました。

2022-04-13 03:46 UTC, azusa-f commented on lib/youtube/youtube_screen.dart
> +  List<Widget> _buildVideoItems(videoItems) {
型書きました。

2022-04-13 03:47 UTC, azusa-f commented
> lib/mvvm/model/qiita_item.freezed.dart このファイルを削除していますが、qiitaAPIの画面はちゃんと動作しますか？

動作しなさそうなので、戻しました。

修正したので、再度確認お願いいたします。

2022-04-14 07:26 UTC, t-nakata approved these changes

2022-04-14 12:10 UTC, merged