WIP
azusa-f/flutter-tutorial pull request #17
Opened 2022-05-11 01:10 UTC by azusa-f

2022-05-22 14:08 UTC, t-nakata requested changes
結構多いですがコメント確認してください

2022-05-22 14:08 UTC, t-nakata commented on lib/money_diary/money_diary_screen.dart
> +      ),
`moneyDiaryMainColor`と並べて宣言したほうがきれいなように思いました。

2022-05-22 14:08 UTC, t-nakata commented on lib/money_diary/money_diary_screen.dart
> +  );
`moneyDiaryMainColor`を`MoneyDiaryHome`以外から参照する予定がないならPrivateに変更してください

2022-05-22 14:08 UTC, t-nakata commented on lib/money_diary/money_diary_screen.dart
> +  }
メソッドの並び順として、あんまり良くないなと思いました。
しっかりとしたルールがあるわけではないですが、慣習として下記のような順番に並べるといいと思います。

1. superクラスの overrideメソッド
2. interfaceのoverrideメソッド
3. クラスのPublicメソッド
4. クラスのPrivateメソッド

今回の場合`_onTapItem`メソッドは `_buildBottomNavigationBar`からのみ参照されているので、
`_buildBottomNavigationBar`のしたに書くのがいいと思います。

2022-05-22 14:08 UTC, t-nakata commented on lib/money_diary/money_diary_screen.dart
> +  Future _showEditDialog(BuildContext context, Color moneyDiaryMainColor) {
`moneyDiaryMainColor`はメソッド内で参照されていないです、削除してください。

2022-05-22 14:08 UTC, t-nakata commented on lib/money_diary/money_diary_screen.dart
> +        });
```
});
```
↓
```
  },
);
```

2022-05-22 14:08 UTC, t-nakata commented on lib/money_diary/money_diary_screen.dart
> +        ),
labelの値ですが、`_appBarTitleList `と同じ値を使用するなら、別途定数を作るか
`_appBarTitleList`の値を使用してください

2022-05-22 14:08 UTC, t-nakata commented on lib/money_diary/money_diary_screen.dart
> +class MoneyDiaryHome extends StatefulWidget {
ファイル名とクラス名は基本的に同じ名前にしてください。
`money_diary_scree.dart`なら `MoneyDiaryScreen`としてください。

2022-05-22 14:08 UTC, t-nakata commented on lib/money_diary/money_diary_screen.dart
> +class PaymentAddButton extends ConsumerWidget {
このクラス名は実態とずれているともうので名前を考え直してください

2022-05-22 14:08 UTC, t-nakata commented on lib/money_diary/money_diary_screen.dart
> +  ) {
メソッド名が実態と合っていないので修正してください

2022-05-22 14:08 UTC, t-nakata commented on lib/money_diary/money_diary_screen.dart
> +              ),
moneyDiaryMainColorを参照すればいいような気がします

2022-05-22 14:08 UTC, t-nakata commented on lib/money_diary/payment_dialog.dart
> +class PaymentEditDialog extends StatefulWidget {
このクラス名も実態と合っていないので修正してください。
ダイアログではなく、ダイアログの中身のWidgetを生成している

それにふさわしい名前にしてください。

2022-05-22 14:08 UTC, t-nakata commented on lib/money_diary/payment_list.dart
> +    return Stack(
ListViewしか入っていないのにStackを使う理由はなさそうですがなにか意図はありますか？

2022-05-22 14:08 UTC, t-nakata commented on lib/money_diary/payment_totalling_screen.dart
> +    //var test = paymentItems.where((payment) => payment.category == '家賃');
不要なコードならコメントアウトではなく削除してください

2022-05-22 14:08 UTC, t-nakata commented on lib/money_diary/payment_totalling_screen.dart
> +class PaymentTotalling extends ConsumerWidget {
クラス名はファイル名と一致するように修正してください

2022-05-22 14:08 UTC, t-nakata commented on lib/money_diary/payment_totalling_screen.dart
> +    return Stack(
ここもStackを使う理由はなさそうです

2022-05-23 03:13 UTC, azusa-f commented on lib/money_diary/money_diary_screen.dart
> +      ),
_backGroundColorとして宣言しました

2022-05-23 03:13 UTC, azusa-f commented on lib/money_diary/money_diary_screen.dart
> +  );
別クラスから参照することになったので、そのままにしました

2022-05-23 03:13 UTC, azusa-f commented on lib/money_diary/money_diary_screen.dart
> +  }
指示通りに変更しました

2022-05-23 03:13 UTC, azusa-f commented on lib/money_diary/money_diary_screen.dart
> +  Future _showEditDialog(BuildContext context, Color moneyDiaryMainColor) {
削除しました

2022-05-23 03:14 UTC, azusa-f commented on lib/money_diary/money_diary_screen.dart
> +        });
承知いたしました

2022-05-23 03:14 UTC, azusa-f commented on lib/money_diary/money_diary_screen.dart
> +        ),
_appBarTitleListを使用しました

2022-05-23 03:14 UTC, azusa-f commented on lib/money_diary/money_diary_screen.dart
> +class MoneyDiaryHome extends StatefulWidget {
承知いたしました

2022-05-23 03:14 UTC, azusa-f commented on lib/money_diary/money_diary_screen.dart
> +              ),
承知いたしました

2022-05-23 03:15 UTC, azusa-f commented on lib/money_diary/payment_list.dart
> +    return Stack(
必要なかったので削除しました

2022-05-23 03:15 UTC, azusa-f commented on lib/money_diary/payment_totalling_screen.dart
> +    //var test = paymentItems.where((payment) => payment.category == '家賃');
削除しました

2022-05-23 03:26 UTC, azusa-f commented on lib/money_diary/payment_totalling_screen.dart
> +    return Stack(
削除しました

2022-05-23 03:29 UTC, azusa-f commented on lib/money_diary/payment_dialog.dart
> +class PaymentEditDialog extends StatefulWidget {
PaymentEditForm にしました

2022-05-23 03:50 UTC, azusa-f commented on lib/money_diary/money_diary_screen.dart
> +class PaymentAddButton extends ConsumerWidget {
PaymentEditDialog にしました

2022-05-23 04:07 UTC, azusa-f commented on lib/money_diary/money_diary_screen.dart
> +  ) {
_paymentEditForm にしました

2022-05-23 04:07 UTC, azusa-f commented
@t-nakata 
レビューありがとうございました。
修正したので、お手隙の際にご確認お願いいたします。

2022-05-24 00:46 UTC, t-nakata commented on lib/money_diary/money_diary_screen.dart
> +class PaymentAddButton extends ConsumerWidget {
実態と合ってないので `~~Widget`という名前にしてください。

2022-05-24 00:48 UTC, t-nakata commented on lib/money_diary/money_diary_screen.dart
> +    const PaymentTotallingScreen(),
同じ階層のタブなので名前も同じようにつけた方がいいです。

2022-05-24 00:49 UTC, t-nakata approved these changes

2022-05-24 01:18 UTC, azusa-f commented on lib/money_diary/money_diary_screen.dart
> +class PaymentAddButton extends ConsumerWidget {
PaymentAddWidget　にしました

2022-05-24 01:24 UTC, azusa-f commented on lib/money_diary/payment_totalling_screen.dart
> +class PaymentTotalling extends ConsumerWidget {
承知いたしました。

2022-05-24 01:39 UTC, azusa-f commented on lib/money_diary/money_diary_screen.dart
> +    const PaymentTotallingScreen(),
承知いたしました

2022-05-24 01:42 UTC, merged