【Flutter研修: Tutorial1】アニメーション
azusa-f/flutter-tutorial pull request #3
Opened 2022-03-17 05:08 UTC by azusa-f

### 概要
flutter公式チュートリアルに沿って、
アニメーションを作成
公式チュートリアルURL：https://docs.flutter.dev/development/ui/animations/tutorial

### 仕様
・Flutterのロゴが２秒かけて大きくなったり小さくなったりするアニメーション
https://user-images.githubusercontent.com/98789438/158741210-cbc668ea-f14a-4aeb-a5b4-c8d01323d56e.mov

2022-03-17 06:11 UTC, onishitaisei commented
@azusa-f 
数件コメントします！

まず、トップレベル関数のmain()は1アプリに対して1つのイメージでお願いします！もし、他の画面を表示させたい場合は画面を遷移させて表示させてください。画面遷移については下記のドキュメントが参考になります。
https://docs.flutter.dev/cookbook/navigation/navigation-basics
また、ファイル名がmain_2.dartだとこのファイルが何をしているのかが分かりずらいため、もう少し具体的な命名でお願いします！（コミットメッセージもanimationだけだと分からないため、どんな実装や修正を行ったか具体的にお願いします🙇‍♂️）

次にプルリクについてですが、添付いただいている動画がダウンロードしないと見れない形式になっているので、すぐに見れる形に修正お願いします🙇‍♂️（おそらく添付URLの上部に空白がないのが原因だと思うので、上部に空白を入れてみてください）

2022-03-18 06:47 UTC, azusa-f commented
@onishitaisei 
ありがとうございます。

・main()１つにして、目次画面を作成して、そこからanimationに遷移するようにしました。
・ファイル名変えました。
・動画をすぐに見られるようにしました。

よろしくお願いします！

2022-03-18 06:58 UTC, t-nakata requested changes

2022-03-18 06:58 UTC, t-nakata commented on lib/main.dart
> +class PageChanege extends StatelessWidget {
`PageChanege` というクラス名は適切じゃないように思います。
自分がつけるなら目次ページなので `IndexPage`などとつけます

2022-03-18 06:58 UTC, t-nakata commented on lib/main.dart
> +                child: const Text("flutter_tutorial"),
"flutter_tutorial" ユーザーの目に見えるものなので、SnakeCaseとかは使わないようにしてください。
あと "flutter_tutorial"ボタンをタップしたらアニメーションの画面に遷移するのは不自然だと思います。
`AnimationTutorial`ボタンをおしてアニメーションの画面に遷移するならわかる気がします。

2022-03-18 06:58 UTC, t-nakata commented on lib/tutorial_1/animation.dart
> +        duration: const Duration(seconds: 2), vsync: this); //2秒で変化させる
`vsync: this);`ここの thisのあとに `,`をついかしてフォーマッターを実行してください

2022-03-18 06:58 UTC, t-nakata commented on pubspec.yaml
> +  provider: ^5.0.0
これって何に使ってますか？

2022-03-18 07:05 UTC, azusa-f commented on lib/main.dart
> +class PageChanege extends StatelessWidget {
IndexPageにします。

2022-03-18 07:06 UTC, azusa-f commented on lib/main.dart
> +                child: const Text("flutter_tutorial"),
AnimationTutorial にします。

2022-03-18 07:07 UTC, azusa-f commented on lib/tutorial_1/animation.dart
> +        duration: const Duration(seconds: 2), vsync: this); //2秒で変化させる
承知いたしました。

2022-03-18 07:11 UTC, azusa-f commented on pubspec.yaml
> +  provider: ^5.0.0
何かのエラーを修正するときに、
providerを入れたら治ると見たので追記してインストールしました。
結局治らなくて使ってないので、消します。

2022-03-18 07:37 UTC, t-nakata commented on lib/tutorial_1/animation.dart
> +class AnimationPage extends StatelessWidget {
このクラスのファイル名ですが、`animation.dart`となっていますが、ファイル名はクラス名をSnakeCaseで記述したものとなります、今回の場合メインとなる`AnimationPage`クラスから`animation_page.dart`とするのが一般的です。

修正してください。

2022-03-18 07:42 UTC, azusa-f commented on lib/tutorial_1/animation.dart
> +class AnimationPage extends StatelessWidget {
修正しました。

2022-03-18 07:43 UTC, t-nakata approved these changes

2022-03-22 01:47 UTC, onishitaisei approved these changes

2022-03-22 01:53 UTC, merged