【Flutter研修: Tutorial3.1】youtube画面：クラスとダミーデータを使って動的に表示
azusa-f/flutter-tutorial pull request #7
Opened 2022-04-01 09:53 UTC by azusa-f

### 概要
・Flutter研修　[Tutorial3.1~3.3  - クラスとダミーデータを作って前回作成した画面を動的に表示してみよう。](https://www.notion.so/Tutorial3-29d7577628ff429d95a2a7f7f402fc22)に沿って、youtubeの画面を模したものを作成。

### 仕様
・MovieInfoクラスとダミーデータを作成した。
・ダミーデータでコンテンツを表示させる。
<img src='https://user-images.githubusercontent.com/98789438/161240491-7a715ddf-4256-4ad4-bdfa-6e16c983f80f.png' width="200">

2022-04-03 09:29 UTC, t-nakata commented
通常は下記にてレビューします。
https://github.com/azusa-f/flutter-tutorial/pull/7/files

現状だと何を修正したのかが分かりづらいです。
`feature`ブランチは基本的には `develop`からブランチ切って修正を加え`develop`へのPRを行います。

まだ`develop`へマージされていない別の`feature`ブランチの実装に依存した修正をする場合は、
その依存するブランチからブランチを切るようにしてください。

![スクリーンショット 2022-04-03 18 14 15](https://user-images.githubusercontent.com/13247335/161420527-7ec72a8d-c2af-43a3-81d1-1c51a767f9a9.png)
また上記の `file changed`を見て差分がわかりやすいかを確認してからレビュー依頼を出してください。

詳しくは進捗で話しましょう。

2022-04-04 02:53 UTC, t-nakata commented on lib/youtube/youtube_screen.dart
> +  final List<MovieInfo> _createDummyData = [
変数名が同士で始まるとメソッド名と勘違いされることがあるので、同士で始めないようにしてください。

今回の場合だと`dummyVideoData`などがいいと思いました。

あと慣習としてメンバ変数の定義は、クラスの上部で行います。
コンストラクタよりも上に来てほしいので、 3と4行目の間に移動してください。

2022-04-04 02:54 UTC, t-nakata requested changes
コメントしました確認お願いします。

2022-04-04 02:55 UTC, azusa-f commented on lib/youtube/youtube_screen.dart
> +  final List<MovieInfo> _createDummyData = [
承知いたしました。

2022-04-04 03:21 UTC, azusa-f commented
@t-nakata 
修正したので、お手隙の際に再度確認をお願い致します。

2022-04-04 03:24 UTC, t-nakata approved these changes

2022-04-04 03:24 UTC, merged